openapi: 3.0.1
info:
  title: AppFlow
  x-cortex-tag: appflow
  x-cortex-type: service
  description: CI/CD pipeline management for automated app deployments.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: feature-notifications
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
