openapi: 3.0.1
info:
  title: BackupSvc
  x-cortex-tag: backupsvc
  x-cortex-type: service
  description: Automated backup and disaster recovery service.
  x-cortex-owners:
  - name: cjr-org-backend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:cloud
  x-cortex-parents:
  - tag: feature-billing
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
