openapi: 3.0.1
info:
  title: ComputeNest
  x-cortex-tag: computenest
  x-cortex-type: service
  description: High performance computing services for complex data processing.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:cloud
  x-cortex-parents:
  - tag: feature-notifications
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
