openapi: 3.0.1
info:
  title: CostAnalyzer
  x-cortex-tag: costanalyzer
  x-cortex-type: service
  description: Cloud cost analysis and optimization service.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:monitoring
  x-cortex-parents:
  - tag: feature-reporting
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
