openapi: 3.0.1
info:
  title: DeployBot
  x-cortex-tag: deploybot
  x-cortex-type: service
  description: Automated deployment orchestration service.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: feature-notifications
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
