openapi: 3.0.1
info:
  title: DocParser
  x-cortex-tag: docparser
  x-cortex-type: service
  description: Document parsing and structured data extraction service.
  x-cortex-owners:
  - name: cjr-org-backend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: feature-search
  x-cortex-custom-data:
    isManaged: false
servers:
- url: /
