openapi: 3.0.1
info:
  title: ErrorTracker
  x-cortex-tag: errortracker
  x-cortex-type: frontend
  description: Frontend error tracking and session replay tool.
  x-cortex-owners:
  - name: cjr-org-frontend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:monitoring
  x-cortex-parents:
  - tag: catalog-frontend
  x-cortex-custom-data:
    framework: React
    applicationType: spa
    designSystem: Material UI
    bundler: Vite
    supportedBrowsers:
    - Chrome
    - Firefox
servers:
- url: /
