openapi: 3.0.1
info:
  title: FeatureFlag
  x-cortex-tag: featureflag
  x-cortex-type: service
  description: Feature flag management and rollout service.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: feature-notifications
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
