openapi: 3.0.1
info:
  title: MeshProxy
  x-cortex-tag: meshproxy
  x-cortex-type: service
  description: Service mesh proxy and sidecar manager.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:cloud
  x-cortex-parents:
  - tag: feature-notifications
  x-cortex-custom-data:
    isManaged: false
servers:
- url: /
