openapi: 3.0.1
info:
  title: PipelineX
  x-cortex-tag: pipelinex
  x-cortex-type: service
  description: ML data pipeline orchestration service.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:cloud
  x-cortex-parents:
  - tag: feature-search
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
