openapi: 3.0.1
info:
  title: RuleEngine
  x-cortex-tag: ruleengine
  x-cortex-type: service
  description: Business rules evaluation and policy engine.
  x-cortex-owners:
  - name: cjr-org-backend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: feature-billing
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
