openapi: 3.0.1
info:
  title: SecretsVault
  x-cortex-tag: secretsvault
  x-cortex-type: service
  description: Secrets management and automated rotation.
  x-cortex-owners:
  - name: cjr-org-backend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:security
  x-cortex-parents:
  - tag: feature-authentication
  x-cortex-custom-data:
    isManaged: true
servers:
- url: /
