openapi: 3.0.1
info:
  title: TraceGrid
  x-cortex-tag: tracegrid
  x-cortex-type: service
  description: Distributed tracing for microservices.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:monitoring
  x-cortex-parents:
  - tag: feature-reporting
  x-cortex-custom-data:
    isManaged: false
servers:
- url: /
