openapi: 3.0.1
info:
  title: WorkflowEng
  x-cortex-tag: workfloweng
  x-cortex-type: service
  description: Workflow automation and orchestration engine.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: feature-notifications
  x-cortex-custom-data:
    isManaged: false
servers:
- url: /
