openapi: 3.0.1
info:
  title: BillingConsole
  x-cortex-tag: billingconsole
  x-cortex-type: frontend
  description: Billing and subscription management console.
  x-cortex-owners:
  - name: cjr-org-frontend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: catalog-frontend
  x-cortex-definition:
    type: frontend
    framework: React
    applicationType: spa
    designSystem: Material UI
    bundler: Webpack
    supportedBrowsers:
    - Chrome
    - Firefox
servers:
- url: /
