openapi: 3.0.1
info:
  title: NotifyClient
  x-cortex-tag: notifyclient
  x-cortex-type: library
  description: Notification dispatch client SDK.
  x-cortex-owners:
  - name: cjr-org-backend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: catalog-libraries
  x-cortex-definition:
    type: library
    version: 1.0.1
    language: Java
    license: Apache-2.0
    packageManager: maven
    isInternal: true
servers:
- url: /
