# gitops
openapi: 3.0.1
info:
  title: TraceClient
  x-cortex-tag: traceclient
  x-cortex-type: library
  description: OpenTelemetry tracing client library.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:monitoring
  x-cortex-parents:
  - tag: catalog-libraries
  x-cortex-definition:
    type: library
    version: 1.4.0
    language: Go
    license: Apache-2.0
    packageManager: go
    isInternal: true
servers:
- url: /
