openapi: 3.0.1
info:
  title: ConfigLoader
  x-cortex-tag: configloader
  x-cortex-type: library
  description: Environment-aware configuration loader.
  x-cortex-owners:
  - name: cjr-org-platform
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:tooling
  x-cortex-parents:
  - tag: catalog-libraries
  x-cortex-custom-data:
    version: 1.1.0
    language: Python
    license: MIT
    packageManager: pip
    isInternal: true
servers:
- url: /
