openapi: 3.0.1
info:
  title: ComplianceUI
  x-cortex-tag: complianceui
  x-cortex-type: frontend
  description: Compliance reporting and certification portal.
  x-cortex-owners:
  - name: cjr-org-frontend
    type: GROUP
    provider: CORTEX
  x-cortex-groups:
  - infra:security
  x-cortex-parents:
  - tag: catalog-frontend
  x-cortex-custom-data:
    framework: React
    applicationType: spa
    designSystem: Material UI
    bundler: Webpack
    supportedBrowsers:
    - Chrome
    - Firefox
servers:
- url: /
